-- ========= BUAT SKEMA DULU =========
CREATE SCHEMA IF NOT EXISTS dwh;

-- ========= DIMENSIONS (DALAM SKEMA DWH) =========

-- 1. DimDate
CREATE TABLE IF NOT EXISTS dwh.DimDate (
    DateID INT PRIMARY KEY,
    FullDate DATE NOT NULL,
    Day INT,
    Month INT,
    MonthName VARCHAR(20),
    Quarter INT,
    Year INT,
    DayOfWeek VARCHAR(20),
    IsHoliday BOOLEAN,
    HolidayName VARCHAR(100)
);

-- 2. DimProduct
CREATE TABLE IF NOT EXISTS dwh.DimProduct (
    ProductID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ProductID_OLTP INT,
    ProductName VARCHAR(255),
    Price DECIMAL(10, 2),
    CategoryName VARCHAR(100),
    Class VARCHAR(100),
    IsAllergic VARCHAR(50)
);

-- 3. DimCustomer
CREATE TABLE IF NOT EXISTS dwh.DimCustomer (
    CustomerID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    CustomerID_OLTP INT,
    CustomerName VARCHAR(255),
    Address VARCHAR(255),
    CustomerCityName VARCHAR(100),
    CustomerCountryName VARCHAR(100)
);

-- 4. DimEmployee
CREATE TABLE IF NOT EXISTS dwh.DimEmployee (
    EmployeeID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    EmployeeID_OLTP INT,
    EmployeeName VARCHAR(255),
    Gender VARCHAR(20),
    HireDate DATE
);

-- 5. DimLocation
CREATE TABLE IF NOT EXISTS dwh.DimLocation (
    LocationID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    CityID_OLTP INT,
    CityName VARCHAR(100),
    CountryName VARCHAR(100)
);

-- 6. DimWeather
CREATE TABLE IF NOT EXISTS dwh.DimWeather (
    WeatherID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Condition VARCHAR(100),
    Temperature_C INT,
    FeelsLike_C INT,
    Wind_kph DECIMAL(5, 2),
    Precip_mm DECIMAL(5, 2),
    IsDay INT,
    DateID INT,
    LocationID INT
);

-- ========= FACT TABLE (DALAM SKEMA DWH) =========
CREATE TABLE IF NOT EXISTS dwh.FactSales (
    SalesID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    DateID INT REFERENCES dwh.DimDate(DateID),
    WeatherID INT REFERENCES dwh.DimWeather(WeatherID),
    ProductID INT REFERENCES dwh.DimProduct(ProductID),
    CustomerID INT REFERENCES dwh.DimCustomer(CustomerID),
    EmployeeID INT REFERENCES dwh.DimEmployee(EmployeeID),
    LocationID INT REFERENCES dwh.DimLocation(LocationID),
    
    Quantity INT NOT NULL,
    TotalPrice DECIMAL(10, 2) NOT NULL,
    Discount DECIMAL(10, 2)
);